"""init semua tabel

Revision ID: 6652de048f28
Revises: 
Create Date: 2026-04-17 10:41:03.084245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6652de048f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('benar', 'salah'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_activity', sa.Integer(), nullable=True),
    sa.Column('nilai_akhir', sa.Float(), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=True),
    sa.Column('waktu_mengerjakan', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_benar', sa.Integer(), nullable=True),
    sa.Column('total_salah', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('MC_option', sa.Text(), nullable=True),
    sa.Column('MC_Answer', sa.String(length=10), nullable=True),
    sa.Column('SA_Answer', sa.Text(), nullable=True),
    sa.Column('tingkat_kesulitan', sa.Enum('mudah', 'sedang', 'sulit'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_other', sa.String(length=50), nullable=True),
    sa.Column('type_id_other', sa.Enum('NIM', 'NIDN', name='id_other_types'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('Student', 'Teacher', name='user_roles'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semester', sa.Enum('ganjil', 'genap', name='semester_enum'), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('progres_value', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_topic', sa.Integer(), nullable=False),
    sa.Column('sub_topic_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('aktivitas', 'kuis', 'evaluasi', name='activity_type'), nullable=False),
    sa.Column('durasi_pengerjaan', sa.Integer(), nullable=True),
    sa.Column('jumlah_soal', sa.Integer(), nullable=True),
    sa.Column('id_topic', sa.Integer(), nullable=True),
    sa.Column('id_subtopic', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('aktif', 'tidak aktif', name='activity_status'), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['id_subtopic'], ['sub_topic.id'], ),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_topic', sa.Integer(), nullable=False),
    sa.Column('id_subtopic', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_subtopic'], ['sub_topic.id'], ),
    sa.ForeignKeyConstraint(['id_topic'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.Column('nilai_kkm_kuis', sa.Integer(), nullable=False),
    sa.Column('nilai_kkm_evaluasi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id_class')
    )
    op.create_table('student_classes',
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_student', 'id_class')
    )
    op.create_table('teacher_classes',
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('id_class', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_teacher', 'id_class')
    )
    op.create_table('activity_question',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id_activity', 'id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_question')
    op.drop_table('teacher_classes')
    op.drop_table('student_classes')
    op.drop_table('settings')
    op.drop_table('history_progress')
    op.drop_table('activities')
    op.drop_table('sub_topic')
    op.drop_table('progress')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('topic')
    op.drop_table('question')
    op.drop_table('activity_result')
    op.drop_table('activity_answer')
    # ### end Alembic commands ###
