"""init

Revision ID: ad472a7a06b2
Revises: 
Create Date: 2026-04-06 09:39:10.084357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad472a7a06b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('latihan', 'evaluasi'), nullable=True),
    sa.Column('durasi_pengerjaan', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('jumlah_soal', sa.Integer(), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('MC_option', sa.Text(), nullable=True),
    sa.Column('MC_Answer', sa.String(length=10), nullable=True),
    sa.Column('SA_Answer', sa.Text(), nullable=True),
    sa.Column('tingkat_kesulitan', sa.Enum('mudah', 'sedang', 'sulit'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_question',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('id_question', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_activity'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id_activity', 'id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_question')
    op.drop_table('question')
    op.drop_table('activities')
    # ### end Alembic commands ###
